# the first thing GitLab Runner will look for in your .gitlab-ci.yml is a Docker image specifying what do you need in your container to run that script
image: node:18.16.0 # can be upgraded, depending on your node version used

cache: #  Parameter 'cache' to cache the installation files for your projects dependencies, for building faster
  paths:
    - node_modules/

stages:
  - prepare
  - test
  - build-storybook
  - deploy

prepare:
  stage: prepare
  script:
    - npm ci
  only:
    - master # or dev, the branch you want to publish

lint:
  stage: test
  script: npm run lint
  only:
    - master # or dev, the branch you want to publish

ts:
  stage: test
  script: npm run check
  only:
    - master # or dev, the branch you want to publish

test:
  stage: test
  script: npm run test
  only:
    - master # or dev, the branch you want to publish

format:
  stage: test
  script: npm run format-check
  only:
    - master # or dev, the branch you want to publish

build-storybook:
  stage: build-storybook
  script:
    - make rm-int-stories # Delete internal stories (that ones like ...internal.stories.ts|mdx)
    - npm run build-storybook
  artifacts:
    paths:
      - storybook-static
  only:
    - master # or dev, the branch you want to publish

pages:
  stage: deploy
  script:
    - ls storybook-static
    - mkdir .public
    - cp -r storybook-static/* .public
    - rm -rf .public/node_modules
    - rm -rf public/*
    - mv .public public
    - ls public
  artifacts:
    paths:
      - public # mandatory, other folder won't work
  only:
    - master # or dev, the branch you want to publish
