version: '3'
services:
  app:
    container_name: planfy-front
    image: node:14.18.3
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - '6006:6006'
    user: 1000:1000
    tty: true
